# Generated by Django 5.0.6 on 2024-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Streetnumber'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
