# Generated by Django 5.0.6 on 2024-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_city_myuser_country_myuser_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='number',
            new_name='street_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phonenumber'),
        ),
    ]
