# Generated by Django 5.0.6 on 2024-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_number_myuser_street_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='my_videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
