# Generated by Django 5.0.6 on 2024-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_phone_number_alter_myuser_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='video_timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
