# Generated by Django 5.0.6 on 2024-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoitem_created_at_videoitem_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
