# Generated by Django 5.0.6 on 2024-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videoitem_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
