# Generated by Django 5.0.6 on 2024-10-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videoitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True),
        ),
    ]
